### ISSUE TITLE
Group plug-ins do not work

### ISSUE THREAD

**Issue by estudieno** [roughsmoothengine/organize-series#57] opened 2018-08-01 15:20 UTC
After the transition to the new license system, Groups - Single Site plug-ins do not work anymore. In WordPress Dashboard, I only get the first group I've created instead of all 15 groups I've created and worked previously.

Also created 15 different group pages to list all article series in each category. The page is generated from a script I received from the developer. The script is as follows:

`<?php 
$args = array('include' => array( '1132' ), 'order' => 'ASC' );
$get_series_args = array( 'hide_empty' => 1);

$groups = get_series_groups( $args );
foreach ( $groups as $group ) {
echo '<div class="entry post clearfix">';
echo '<h3 id="group-title-'.$group->term_id.'" class="group-title">'.$group->name.'</h3>';

$get_series = get_series_in_group($group->term_id, $get_series_args);

$series_args = array( 'include' => $get_series, 'order' => 'ASC' );

wp_serieslist_display(false, $series_args);

echo '</div>';
}
?>`

These pages do not work either. In fact, neither the logo, the top, or the content are loaded. An example of how these pages are now displayed can be seen here: https://estudie.no/gruppen-aksjer/

Have tried sending mail to support but have not heard anything yet. Why does this happen and what needs to be done to correct the mistake that has occurred?

**Comment by nerrad** [comment] 2019-01-06 02:48
Hi there,

Sorry for the delay in getting back to you.  I also apologize for not responding to your email.  I just did a search and it looks like I was on vacation when it was sent back in August and somehow it got archived so I didn't see it when I got back.

I've just been taking some time to triage things right now hence the delay in responding.

Regarding your issue, I'm unable to reproduce on my test sites with the latest versions of Organize Series and Organize Series Groups running in a PHP 7.3 server environment. I'm not sure what's happening in your case but the upgrade shouldn't have affected anything as there were no database changes (just a few changes to the bootstrapping process and the licensing changes).  It sounds like there may have been something else changed/modified on your site around the same time as any OS upgrades.

I'm closing this issue because this repository is for the Organize Series Core plugin, not the groups add-on.  Feel free to email support if you are still experiencing issues but just a reminder that the [basic support license](https://organizeseries.com/downloads/support-license/) is required for any support requests.

**Closed by nerrad** 2019-01-06 02:48 UTC
